# Generated by Django 4.1.3 on 2023-05-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
