# Generated by Django 4.1.3 on 2023-05-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
