# Generated by Django 4.1.3 on 2023-05-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='active',
            new_name='is_active',
        ),
    ]
