# Generated by Django 4.1.3 on 2023-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_guest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
